export const locations = [
    'London',
    'Newcastle Upon Tyne',
    'Belfast',
    'Leicester',
    'Norwich',
    'Reading',
    'Doncaster',
    'Wolverhampton',
    'Brighton',
    'Oxford',
    'Manchester',
    'Liverpool',
    'Edinburgh',
    'Aberdeen',
    'Swansea',
    'Leeds',
    'York',
    'Stoke On Trent',
    'Plymouth',
    'Exeter',
    'Birmingham',
    'Bristol',
    'Nottingham',
    'Coventry',
    'Northampton',
    'Hull',
    'Bolton',
    'Luton',
    'Warrington',
    'Portsmouth',
    'Glasgow',
    'Sheffield',
    'Cardiff',
    'Southampton',
    'Peterborough',
    'Bradford',
    'Derby',
    'Milton keynes',
    'Cambridge',
    'Middlesbrough'
];

export const services = [
    'Accountants',
    'Architects',
    'Barbers',
    'Beauty Salons',
    'Boarding Kennels',
    'Builders',
    'Cafes & Coffee Shops',
    'Car Body Repairs',
    'Carpenters & Joiners',
    'Charity Shops',
    'Chinese Takeaways',
    'Day Nurseries',
    'Dentists',
    'Doctors (Medical Practicioners)',
    'Domestic Cleaning',
    'Driving Schools',
    'Dry Cleaners',
    'Electricians',
    'Estate Agents',
    'Farmers',
    'Fencing Services',
    'Florists',
    'Function Rooms & Banqueting',
    'Furniture Shops',
    'Garage Services',
    'Garden Services',
    'Gas Engineers',
    'Grocers & Convenience Stores',
    'Hairdressers',
    'Hotels',
    'Indian Restaurants',
    'Mobile Hair Dressers',
    'Mobile Phone Repairs',
    'Mortgages',
    'MOT Testing',
    'Newsagents',
    'Painters & Decorators',
    'Pharmacies',
    'Plumbers',
    'Pubs',
    'Restaurants',
    'Roofing Services',
    'Skip Hire',
    'Solicitors',
    'Supermarkets',
    'Takeaway Food',
    'Taxis & Private Hire Vehicles',
    'Tyres',
    'Vets',
    'Window Cleaners'
];

export const surnames = [
    'Smith',
    'Johnson',
    'Williams',
    'Jones',
    'Brown',
    'Davis',
    'Miller',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
    'Martin',
    'Thompson',
    'Garcia',
    'Martinez',
    'Robinson',
    'Clark',
    'Rodriguez',
    'Lewis',
    'Lee',
    'Walker',
    'Hall',
    'Allen',
    'Young',
    'Hernandez',
    'King',
    'Wright',
    'Lopez',
    'Hill',
    'Scott',
    'Green',
    'Adams',
    'Baker',
    'Gonzalez',
    'Nelson',
    'Carter',
    'Mitchell',
    'Perez',
    'Roberts',
    'Turner',
    'Phillips',
    'Campbell',
    'Parker',
    'Evans',
    'Edwards',
    'Collins'
];

export const firstNames = [
    'Muhammad',
    'Oliver',
    'Noah',
    'Harry',
    'Leo',
    'George',
    'Jack',
    'Charlie',
    'Freddie',
    'Arthur',
    'Alfie',
    'Henry',
    'Oscar',
    'Theo',
    'Archie',
    'Jacob',
    'Joshua',
    'James',
    'Ethan',
    'Thomas',
    'William',
    'Logan',
    'Lucas',
    'Jackson',
    'Max',
    'Olivia',
    'Sophia',
    'Amelia',
    'Lily',
    'Emily',
    'Ella',
    'Isla',
    'Mia',
    'Aria',
    'Grace',
    'Isabella',
    'Sophie',
    'Charlotte',
    'Evie',
    'Poppy',
    'Ivy',
    'Alice',
    'Daisy',
    'Chloe',
    'Freya',
    'Sienna',
    'Eva',
    'Harper',
    'Willow'
];

export const businessSuffixes = [
    'Ltd',
    'LLC',
    'PLC',
    'Inc',
    'Corp'
];

export const surnameAugmentations = [
    '& Son',
    '& Sons',
    '& Daughters',
    '& Brothers',
    '& Sisters',
    '& Co'
];

export const streetNames = [
    'High',
    'Station',
    'Main',
    'Park',
    'Church',
    'London',
    'Victoria',
    'Green',
    'Manor',
    'Queens',
    'Kings',
    'New',
    'Grange',
    'Kingsway',
    'Queensway',
    'Windsor',
    'Highfield',
    'Mill',
    'Alexander',
    'York',
    "St. John's",
    'Broadway',
    'Springfield',
    'George',
    'West',
    'North',
    'East',
    'South',
    'Richmond',
    'Stanley',
    'Chester'
];

export const streetTypes = [
    'Street',
    'Road',
    'Lane',
    'Avenue',
    'Grove',
    'Crescent',
    'Green',
    'Park'
];

export const TLDs = [
    '.co.uk',
    '.com'
];

export const emailPrefixes = [
    'info@',
    'enquiries@',
    'service@',
    'sales@'
];

export const areaCodes = [
    '0113',
    '0114',
    '0115',
    '0116',
    '0117',
    '0118',
    '01200',
    '01202',
    '01204',
    '01205',
    '01206',
    '01207',
    '01208',
    '01209',
    '0121',
    '01223',
    '01224',
    '01225',
    '01226',
    '01227',
    '01228',
    '01229',
    '01233',
    '01234',
    '01235'
];