export const locations = [
    'London',
    'Newcastle Upon Tyne',
    'Belfast',
    'Leicester',
    'Norwich',
    'Reading',
    'Doncaster',
    'Wolverhampton',
    'Brighton',
    'Oxford',
    'Manchester',
    'Liverpool',
    'Edinburgh',
    'Aberdeen',
    'Swansea',
    'Leeds',
    'York',
    'Stoke On Trent',
    'Plymouth',
    'Exeter',
    'Birmingham',
    'Bristol',
    'Nottingham',
    'Coventry',
    'Northampton',
    'Hull',
    'Bolton',
    'Luton',
    'Warrington',
    'Portsmouth',
    'Glasgow',
    'Sheffield',
    'Cardiff',
    'Southampton',
    'Peterborough',
    'Bradford',
    'Derby',
    'Milton keynes',
    'Cambridge',
    'Middlesbrough'
];

export const services = [
    'Accountants',
    'Architects',
    'Barbers',
    'Beauty Salons',
    'Boarding Kennels',
    'Builders',
    'Cafes & Coffee Shops',
    'Car Body Repairs',
    'Carpenters & Joiners',
    'Charity Shops',
    'Chinese Takeaways',
    'Day Nurseries',
    'Dentists',
    'Doctors (Medical Practicioners)',
    'Domestic Cleaning',
    'Driving Schools',
    'Dry Cleaners',
    'Electricians',
    'Estate Agents',
    'Farmers',
    'Fencing Services',
    'Florists',
    'Function Rooms & Banqueting',
    'Furniture Shops',
    'Garage Services',
    'Garden Services',
    'Gas Engineers',
    'Grocers & Convenience Stores',
    'Hairdressers',
    'Hotels',
    'Indian Restaurants',
    'Mobile Hair Dressers',
    'Mobile Phone Repairs',
    'Mortgages',
    'MOT Testing',
    'Newsagents',
    'Painters & Decorators',
    'Pharmacies',
    'Plumbers',
    'Pubs',
    'Restaurants',
    'Roofing Services',
    'Skip Hire',
    'Solicitors',
    'Supermarkets',
    'Takeaway Food',
    'Taxis & Private Hire Vehicles',
    'Tyres',
    'Vets',
    'Window Cleaners'
];

export const surnames = [
    'Smith',
    'Johnson',
    'Williams',
    'Jones',
    'Brown',
    'Davis',
    'Miller',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
    'Martin',
    'Thompson',
    'Garcia',
    'Martinez',
    'Robinson',
    'Clark',
    'Rodriguez',
    'Lewis',
    'Lee',
    'Walker',
    'Hall',
    'Allen',
    'Young',
    'Hernandez',
    'King',
    'Wright',
    'Lopez',
    'Hill',
    'Scott',
    'Green',
    'Adams',
    'Baker',
    'Gonzalez',
    'Nelson',
    'Carter',
    'Mitchell',
    'Perez',
    'Roberts',
    'Turner',
    'Phillips',
    'Campbell',
    'Parker',
    'Evans',
    'Edwards',
    'Collins'
];

export const firstNames = [
    'Muhammad',
    'Oliver',
    'Noah',
    'Harry',
    'Leo',
    'George',
    'Jack',
    'Charlie',
    'Freddie',
    'Arthur',
    'Alfie',
    'Henry',
    'Oscar',
    'Theo',
    'Archie',
    'Jacob',
    'Joshua',
    'James',
    'Ethan',
    'Thomas',
    'William',
    'Logan',
    'Lucas',
    'Jackson',
    'Max',
    'Olivia',
    'Sophia',
    'Amelia',
    'Lily',
    'Emily',
    'Ella',
    'Isla',
    'Mia',
    'Aria',
    'Grace',
    'Isabella',
    'Sophie',
    'Charlotte',
    'Evie',
    'Poppy',
    'Ivy',
    'Alice',
    'Daisy',
    'Chloe',
    'Freya',
    'Sienna',
    'Eva',
    'Harper',
    'Willow'
];

export const businessSuffixes = [
    'Ltd',
    'LLC',
    'PLC',
    'Inc',
    'Corp'
];

export const surnameAugmentations = [
    '& Son',
    '& Sons',
    '& Daughters',
    '& Brothers',
    '& Sisters',
    '& Co'
];

export const streetNames = [
    'High',
    'Station',
    'Main',
    'Park',
    'Church',
    'London',
    'Victoria',
    'Green',
    'Manor',
    'Queens',
    'Kings',
    'New',
    'Grange',
    'Kingsway',
    'Queensway',
    'Windsor',
    'Highfield',
    'Mill',
    'Alexander',
    'York',
    "St. John's",
    'Broadway',
    'Springfield',
    'George',
    'West',
    'North',
    'East',
    'South',
    'Richmond',
    'Stanley',
    'Chester'
];

export const streetTypes = [
    'Street',
    'Road',
    'Lane',
    'Avenue',
    'Grove',
    'Crescent',
    'Green',
    'Park'
];

export const TLDs = [
    '.co.uk',
    '.com'
];

export const emailPrefixes = [
    'info@',
    'enquiries@',
    'service@',
    'sales@'
];

export const areaCodes = [
    '0113',
    '0114',
    '0115',
    '0116',
    '0117',
    '0118',
    '01200',
    '01202',
    '01204',
    '01205',
    '01206',
    '01207',
    '01208',
    '01209',
    '0121',
    '01223',
    '01224',
    '01225',
    '01226',
    '01227',
    '01228',
    '01229',
    '01233',
    '01234',
    '01235'
];

export const loremIpsumPassages = [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
    'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',
    'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
    'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga',
    'Et harum quidem rerum facilis est et expedita distinctio.',
    'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.',
    'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.'
];

export const reviewTitles = [
    [
        'AVOID!',
        'Very poor service',
        'I cannot recommend this business',
        'I was left wanting'
    ],
    [
        'Mixed feelings',
        'Good, but flawed',
        'Not sure if I could recommend',
        'Some aspects lacking' 
    ],
    [
        'A nice experience',
        'I would use this business again',
        'Satisfactory service',
        'No complaints'
    ],
    [
        'Very pleased',
        'A great local business',
        'Strongly recommend',
        'I will definitely be returning'
    ],
    [
        'Amazing!',
        'Brilliant service',
        '5 star service',
        'Cannot recommend enough!'
    ]
];