export const popularLocations = [
    'London',
    'Newcastle Upon Tyne',
    'Belfast',
    'Leicester',
    'Norwich',
    'Reading',
    'Doncaster',
    'Wolverhampton',
    'Brighton',
    'Oxford',
    'Manchester',
    'Liverpool',
    'Edinburgh',
    'Aberdeen',
    'Swansea',
    'Leeds',
    'York',
    'Stoke On Trent',
    'Plymouth',
    'Exeter',
    'Birmingham'
];

export const searchablePopularLocations = popularLocations.map(el => el.toLowerCase()).sort();

export const popularServices = [
    'Accountants',
    'Airport Transfers',
    'Barbers',
    'Bars & Wine Bars',
    'Bookkeeping Services',
    'Cafes & Coffee Shops',
    'Car Body Repairs',
    'Conference Facilities & Services',
    'Dental Implants',
    'Dentists',
    'Electrical Inspecting & Testing',
    'Electricians',
    'Emergency Electricians',
    'Family Law',
    'Garage Services',
    'Grocers & Convenience Stores',
    'Hairdressers',
    'Legal Services',
    'Mini Cabs',
    'Mobile Hairdressers',
    'MOT Testing',
    'Newsagents',
    'Newspapers & Magazines',
    'Pub Restaurants',
    'Pubs',
    'Root Canal Treatment',
    'Solicitors',
    'Tax Advisers',
    'Taxis & Private Hire Vehicles',
    'Tea & Coffee Specialist Shops'
];

export const searchablePopularServices = popularServices.map(el => el.toLowerCase());